Repository yaptide/yaptide, pull requests merged in 2023-10, with the labels that each got.

#586 Update openapi.yaml
  yaptide/static/openapi.yaml
Labels: EuroHPC

#621 Fix help messege for add-cluster command
  yaptide/admin/db_manage.py
Labels: low priority, python

#626 documentation update
  .gitignore
  docs/gen_ref_pages.py
  docs/index.md
  docs/mkdocs.md
  docs/swagger.md
  mkdocs.yml
Labels: EuroHPC

#631 windows linux tabs
  docs/mkdocs.md
  mkdocs.yml
Labels: EuroHPC

#650 adjust dockerfile and script for worker
  Dockerfile-worker
  docker-compose.yml
  run_worker.sh
  tests/integration/conftest.py
  tests/test_download_shieldhit.py
  tests/test_download_topas.py
  yaptide/admin/simulators.py
Labels: feature

#656 Introduction of UNKNOWN state
  docs/states.md
  mkdocs.yml
  tests/test_database.py
  yaptide/persistence/models.py
  yaptide/routes/batch_routes.py
  yaptide/routes/celery_routes.py
  yaptide/routes/common_sim_routes.py
  yaptide/routes/utils/utils.py
  yaptide/utils/enums.py
  yaptide_tester/yaptide_tester.py
Labels: EuroHPC

#660 Keycloak token validation
  docker-compose.yml
  tests/test_keycloak_tokens.py
  yaptide/routes/keycloak_routes.py
  yaptide/routes/utils/decorators.py
  yaptide/routes/utils/tokens.py
Labels: feature, EuroHPC

#672 improved logging
  yaptide/routes/keycloak_routes.py
Labels: EuroHPC

#663 644 run fluka simulation
  Dockerfile-worker
  requirements.txt
  run_worker.sh
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/test_celery.py
  yaptide/celery/tasks.py
  yaptide/celery/utils/manage_tasks.py
  yaptide/celery/utils/pymc.py
  yaptide/fake/rfluka
  yaptide/routes/celery_routes.py
Labels: Fluka

#664 Deploy Fluka binary to backend from S3 object
  .github/workflows/manual-test.yml
  .github/workflows/test-run.yml
  .pre-commit-config.yaml
  Dockerfile-worker
  README.md
  docs/index.md
  docs/simulator_binaries.md
  mkdocs.yml
  requirements-test.txt
  run_worker.sh
  tests/integration/conftest.py
  tests/test_download_shieldhit.py
  tests/test_download_topas.py
  tests/test_encrypt_decrypt.py
  yaptide/admin/__init__.py
  yaptide/admin/db_manage.py
  yaptide/admin/simulator_storage.py
  yaptide/admin/simulators.py
  yaptide/celery/tasks.py
Labels: Fluka

#689 check if we have access to yaptide
  tests/test_keycloak_tokens.py
  yaptide/routes/keycloak_routes.py
Labels: EuroHPC
