Repository yaptide/yaptide, pull requests merged in 2023-11, with the labels that each got.

#696 667 commiting not empty dot env files
  .pre-commit-config.yaml
  .pre_commit_hooks/__init__.py
  .pre_commit_hooks/check_not_empty_files.py
Labels: Fluka

#695 improved handling of missing certs
  yaptide/batch/batch_methods.py
  yaptide/persistence/models.py
  yaptide/routes/keycloak_routes.py
Labels: EuroHPC

#575 general rework of simulation and worker execution
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/test_run_crashing_simulation.py
  tests/integration/test_run_simulation.py
  tests/test_download_shieldhit.py
  yaptide/admin/simulators.py
  yaptide/application.py
  yaptide/batch/watcher.py
  yaptide/celery/tasks.py
  yaptide/celery/utils/manage_tasks.py
  yaptide/celery/utils/pymc.py
  yaptide/celery/utils/requests.py
  yaptide/celery/worker.py
  yaptide/persistence/db_methods.py
  yaptide/routes/celery_routes.py
  yaptide/routes/common_sim_routes.py
Labels: EuroHPC, Fluka

#692 configure yaptide dockerfiles to use fluka binaries from s3
  .github/workflows/test-run.yml
  run_worker.sh
  tests/conftest.py
  tests/test_download_fluka.py
  tests/test_download_shieldhit.py
  tests/test_download_topas.py
  yaptide/admin/simulator_storage.py
Labels: Fluka

#718 Run fluka input from direct run
  tests/conftest.py
  tests/res/fluka_json_payload_files.json
  tests/res/shieldhit_json_payload_files.json
  tests/test_prepare_simulation.py
  yaptide/utils/sim_utils.py
Labels: Fluka

#706 653 progress bar for fluka
  yaptide/celery/tasks.py
  yaptide/celery/utils/progress/__init__.py
  yaptide/celery/utils/progress/fluka_monitor.py
  yaptide/celery/utils/pymc.py
Labels: Fluka

#683 better error handling
  yaptide/batch/batch_methods.py
Labels: EuroHPC
