Repository yaptide/yaptide, pull requests merged in 2023-08, with the labels that each got.

#518 Fetch Batch results
  yaptide/admin/db_manage.py
  yaptide/routes/auth_routes.py
  yaptide/routes/batch_routes.py
  yaptide/routes/common_sim_routes.py
  yaptide/routes/main_routes.py
  yaptide/routes/utils/decorators.py
  yaptide_tester/yaptide_tester.py
Labels: EuroHPC

#528 fix naming of cluster management
  yaptide/admin/db_manage.py
Labels: EuroHPC

#526 Slurm monitoring
  Dockerfile-flask
  docker-compose.yml
  yaptide/batch/batch_methods.py
  yaptide/batch/string_templates.py
  yaptide/batch/watcher.py
  yaptide/celery/utils/utils.py
  yaptide/persistence/models.py
  yaptide/routes/batch_routes.py
  yaptide/routes/main_routes.py
  yaptide/static/openapi.yaml
Labels: feature, EuroHPC

#533 updates needed for modulator simulations
  .env
  docker-compose.yml
Labels: EuroHPC

#492 Rework Celery workflow
  .github/workflows/test-run.yml
  .gitignore
  pytest.ini
  requirements.txt
  run_worker.sh
  scripts/run_dev_testing.bat
  scripts/run_yaptide.bat
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/test_celery.py
  tests/integration/test_env_manipulation.py
  tests/integration/test_list_simulations.py
  tests/integration/test_run_crashing_simulation.py
  tests/integration/test_run_simulation.py
  tests/test_database.py
  tests/test_download_shieldhit.py
  tests/test_main.py
  yaptide/admin/simulators.py
  yaptide/application.py
  yaptide/batch/batch_methods.py
  yaptide/batch/result_sender.py
  yaptide/batch/string_templates.py
  yaptide/batch/watcher.py
  yaptide/celery/tasks.py
  yaptide/celery/utils/manage_tasks.py
  yaptide/celery/utils/pymc.py
  yaptide/celery/utils/requests.py
  yaptide/celery/utils/utils.py
  yaptide/celery/worker.py
  yaptide/persistence/db_methods.py
  yaptide/persistence/models.py
  yaptide/routes/auth_routes.py
  yaptide/routes/batch_routes.py
  yaptide/routes/celery_routes.py
  yaptide/routes/common_sim_routes.py
  yaptide/routes/keycloak_routes.py
  yaptide/routes/main_routes.py
  yaptide/routes/task_routes.py
  yaptide/routes/user_routes.py
  yaptide/routes/utils/decorators.py
  yaptide/routes/utils/response_templates.py
  yaptide/routes/utils/tokens.py
  yaptide/routes/utils/utils.py
  yaptide/utils/enums.py
  yaptide/utils/sim_utils.py
  yaptide_tester/input_files/beam.dat
  yaptide_tester/yaptide_tester.py
Labels: bug, feature, EuroHPC

#544 Improve tests
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/test_list_simulations.py
  tests/integration/test_run_simulation.py
Labels: EuroHPC
